[package]
name = "chronos"
version = "0.1.0"
edition = "2024"

[lib]
name = "chronos"
path = "src/lib.rs"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
uuid = { version = "1.0", features = ["v4"] }
